node {
 
        def mvnHome
        def dockerHome
        stage('Checkout') {
            git url: 'file://E:/GenC2020/workspace/docker-space/discovery-server',  branch: 'master'
            mvnHome = tool 'Local Maven'
            dockerHome = tool 'MyDocker'
        }

        stage('Build') {
            if (isUnix()) {
                sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
            } else {
                bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
            }
        }

        stage ('Final') {
            build job: 'User-Service-Pipeline', wait: false
        }     

    

}
