FROM openjdk:8-jdk-alpine

ADD target/rest-api-for-docker-test-0.0.1-SNAPSHOT.jar /tmp/rest-api-for-docker-test-0.0.1-SNAPSHOT.jar

CMD ["java","-jar","/tmp/rest-api-for-docker-test-0.0.1-SNAPSHOT.jar"]